sonar.projectKey=viavinmt-tech_python-project-52
sonar.organization=viavinmt-tech

sonar.sources=.
sonar.exclusions=**/migrations/**, **/templates/**, **/static/**, manage.py, **/tests/**, **/settings.py**

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**, **/settings.py**, **/wsgi.py**, **/asgi.py**
