sonar.projectKey=viavinmt-tech_python-project-52
sonar.organization=viavinmt-tech

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=python-project-52
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/static/**,**/migrations/**,**/tests/**,**/settings.py,**/manage.py,**/wsgi.py,**/asgi.py

# Python specific settings
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Encoding of the source code. Default is default system encoding.
sonar.sourceEncoding=UTF-8
