sonar.projectKey=viavinmt-tech_python-project-52
sonar.organization=viavinmt-tech
sonar.projectName=python-project-52
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/static/**,**/migrations/**,**/tests/**,**/settings.py,**/manage.py,**/wsgi.py,**/asgi.py,**/__tests__/**,**/*.spec.ts
sonar.coverage.exclusions=**/tests/**,**/migrations/**,**/settings.py,**/manage.py,**/wsgi.py,**/asgi.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/tests/**/*.py
sonar.issue.ignore.multicriteria.e1.messageKey=hard-coded credential
